# Generated by Django 3.0.6 on 2020-05-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_subsciption_s_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsciption',
            name='support',
            field=models.CharField(choices=[('NO SUPPORT', 'No Support'), ('EMAIL SUPPORT', 'Email Support'), ('CALL & EMAIL SUPPORT', 'Call & Email Support')], default='NO SUPPORT', max_length=30),
        ),
    ]
