# Generated by Django 3.0.6 on 2020-05-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_subsciption_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsciption',
            name='support',
            field=models.CharField(choices=[('No Support', 'No Support'), ('Email Support', 'Email Support'), ('Call & Email Support', 'Call & Email Support')], default='NO SUPPORT', max_length=30),
        ),
    ]
