# Generated by Django 3.0.6 on 2020-05-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200519_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsciption',
            name='center_support',
            field=models.CharField(choices=[('Help Docs. Access', 'Help Docs. Access')], default='Help Docs. Access', max_length=30),
        ),
    ]
