# Generated by Django 3.0.6 on 2020-05-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_subsciption_center_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('user', models.CharField(max_length=15)),
                ('gb', models.CharField(max_length=8)),
                ('s_type', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=10)),
                ('support', models.CharField(choices=[('No Support', 'No Support'), ('Email Support', 'Email Support'), ('Call & Email Support', 'Call & Email Support')], default='NO SUPPORT', max_length=30)),
                ('center_support', models.CharField(choices=[('Help Docs. Access', 'Help Docs. Access')], default='Help Docs. Access', max_length=30)),
            ],
        ),
    ]
